# Generated by Django 6.0.1 on 2026-01-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_withdrawalrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='street_address',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='housing_status',
            field=models.CharField(blank=True, choices=[('OWN', 'Own home'), ('RENT', 'Renting'), ('FAMILY', 'Living with family'), ('MILITARY', 'Military housing'), ('OTHER', 'Other arrangement')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('PARTNERED', 'Domestic partnership'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
