# Generated by Django 6.0.1 on 2026-01-20 12:45

from django.db import migrations, models
from django.utils import timezone


def mark_existing_users_verified(apps, schema_editor):
    User = apps.get_model('loan', 'User')
    User.objects.filter(is_active=True).update(
        email_verified=True,
        email_verified_at=timezone.now(),
    )


def noop(*args, **kwargs):
    """No-op reverse migration."""
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_rename_address_profile_street_address_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_users_verified, noop),
    ]
