# Generated by Django 6.0.1 on 2026-01-24 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_user_email_verified_user_email_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=255)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_last4', models.CharField(blank=True, default='', max_length=8)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='agreements/signatures/')),
                ('signature_text', models.CharField(blank=True, max_length=255)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('terms_version', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='loan.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
